config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :wines, only:[:new, :create, :update, :edit, :show]

  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conso_tag.rb
class ConsoTag < ApplicationRecord
  has_many :wine_consos, dependent: :destroy

  validates :conso_name, presence: true

  def self.random
    @consos = ConsoTag.all
    @consos.sample
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :wine
end

app/models/price.rb
class Price < ApplicationRecord
  has_many :wines

  validates :price_fork, presence: true

  def self.random
    @price = Price.all
    @price.sample
  end

end

app/models/region.rb
class Region < ApplicationRecord
  has_many :wines

  validates :region_name, presence: true

  def self.random
    @regions = Region.all
    @regions.sample
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :wines
  has_many :favorites, dependent: :destroy

  validates :pseudo, uniqueness: true
  validates :pseudo, presence: true

  has_one_attached :photo

end

app/models/wine.rb
class Wine < ApplicationRecord
  belongs_to :user
  belongs_to :price
  belongs_to :region

  has_many :favorites, dependent: :destroy
  has_many :wine_consos, dependent: :destroy

  validates :name, :country, :category, presence: true
  validates :name, uniqueness: true

  COUNTRIES = ["France", "Italie", "Espagne", "Etats-Unis", "Argentine", "Australie", "Chili", "Allemagne", "Afrique du Sud", "Chine"]
  validates :country, inclusion: { in: COUNTRIES }

  CATEGORIES = ["Rouge", "Blanc", "Champagne / Mousseux", "Rosé", "Autre vin", "Autre alcool"]
  validates :category, inclusion: { in: CATEGORIES }

  has_one_attached :photo

  def self.random
    @wines = Wine.all
    @wines.sample
  end

  def self.countries
    @countries = COUNTRIES
  end

  def self.categories
    @categories = CATEGORIES
  end
end

app/models/wine_conso.rb
class WineConso < ApplicationRecord
  belongs_to :wine
  belongs_to :conso_tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo, :photo])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @wines = Wine.all
  end

  def dashboard
    @user = current_user
    @wines = Wine.where(user: current_user)
  end

end

app/controllers/wines_controller.rb
require "open-uri"

class WinesController < ApplicationController

  def new
    @wine = Wine.new
    @countries = Wine.countries
    @categories = Wine.categories
  end

  def create
    @countries = Wine.countries
    @categories = Wine.categories
    @wine = Wine.new(wine_params)
    @wine.user = current_user
    if @wine.valid?
      @wine.save
      if @wine.photo.attached? == false
        img = "https://source.unsplash.com/3uJt73tr4hI"
        file = URI.open(img)
        @wine.photo.attach(io: File.open('app/assets/images/glasses.png'), filename: 'glasses.png', content_type: 'image/png')
      end
      flash[:alert] = "Ton vin est créé!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @wine = Wine.find(params[:id])
  end

  def edit
    @wine = Wine.find(params[:id]) 
    @countries = Wine.countries
    @categories = Wine.categories
  end

  def update
    @countries = Wine.countries
    @categories = Wine.categories
    @wine = Wine.find(params[:id]) 
    if @wine.update(wine_params)
      redirect_to wine_path(@wine)
    else
      render 'edit'
    end
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :description, :user_id, :price_id, :region_id, :country, :photo, :category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyWine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="header-wine-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/aK6WGqxyHFw')">
  <h1>Mes vins</h1>
</div>

<%= render 'shared/cards' %>

app/views/pages/home.html.erb
<%= render 'shared/cards' %>

app/views/shared/_cards.html.erb
<div class="container">
  <div class="cardsgrid">
    <% @wines.each do |wine| %>

      <article class="cardcusto">
        <div class="thumb" style="background-image: url('<%= cl_image_path wine.photo.key, crop: :scale if wine.photo.attached? %>');"> 
        </div>
        <div class="infos">
            <h2 class="title"> <%= wine.name %> </h2>
            <h3 class="date"> <%= wine.region.region_name %> </h3>
            <h3 class="seats"> <%= wine.price.price_fork %> </h3>
            <p class="txt"> <%= wine.description %> </p>
            <%= link_to "Détails", wine_path(wine), class:"details" %>

            <span class="flag"><%= image_tag "#{wine.country}_flag.png" %></span>
        </div>
      </article>

    <% end %>

  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "wine_logo.png" %>
  <% end %>

  <%= link_to new_wine_path, class: "navbar-brand" do %>
    <%= "Ajouter un nouveau vin" %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, height: 50, width: 50, gravity: :face, crop: :thumb, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag  "hero_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "Mes vins", dashboard_path, class: "dropdown-item" %>
      <%= link_to "Modifier mes informations", edit_user_registration_path, class: "dropdown-item" %>
      <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
  <% else %>
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  <% end %>

</div>

app/views/wines/edit.html.erb
<div class="container", style="margin-top:14px">
  <div class="row-forms">
    <div class="column-forms">
      <div class="form-container">

        <%= simple_form_for(@wine) do |f| %>
          <%= f.input :name, label: "Nom du vin" %>
          <%= f.input :description, label: "Décris-le nous un peu:" %>
          <%= f.input :category, collection: @categories, label: "Type de vin" %>
          <%= f.input :country, collection: @countries, label: "Pays" %>
          <%= f.association :region, label_method: :region_name, value_method: :id, label: "Région" %>
          <%= f.association :price, label_method: :price_fork, value_method: :id, label: "Prix" %>
          <%= f.input :photo, as: :file %>
          <div class="form-actions">
            <%= f.button :submit, "Valider" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/wines/new.html.erb
<div class="container", style="margin-top:14px">
  <div class="row-forms">
    <div class="column-forms">
      <div class="form-container">

        <%= simple_form_for(@wine) do |f| %>
          <%= f.input :name, label: "Nom du vin" %>
          <%= f.input :description, label: "Décris-le nous un peu:" %>
          <%= f.input :category, collection: @categories, label: "Type de vin" %>
          <%= f.input :country, collection: @countries, label: "Pays" %>
          <%= f.association :region, label_method: :region_name, value_method: :id, label: "Région" %>
          <%= f.association :price, label_method: :price_fork, value_method: :id, label: "Prix" %>
          <%= f.input :photo, as: :file %>
          <div class="form-actions">
            <%= f.button :submit, "Valider" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/wines/show.html.erb
<div class="header-wine-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @wine.photo.key %>)">
  <h1><%= @wine.name %></h1>
</div>

<div class="container-white">
  <div class="block">
    <div class="block-description">
      <h2>Description</h2>
      <p><%= @wine.description %></p>
    </div>
    <div class="block-tag">
      <p>tags</p> 
    </div>
    <br>
    <br>
    <%= link_to  "Modifier le vin", edit_wine_path(@wine), class:"btn" %>
  </div>

  <div class="block">
    <div class="block-precisions">
      <h2>Détails</h2>
      <p><%= @wine.country %> | <%= @wine.region.region_name %> </p>
      <p><%= @wine.category %> | <%= @wine.price.price_fork %> </p>
    </div>
    <div class="block-avis">
      <h2>Avis</h2>    
    </div> 
  </div>
</div>